[strategy]
kind = "Avellaneda"
preprocessing = "Avellaneda"
symbol = "XBTUSD"

[strategy.avellaneda]
tick_size = 0.01
quote_size = 100
max_position = 1000
gamma = 0.1
delta = 0.2
xi = 0.1

[strategy.avellaneda.vol]
window_len = 500
interval_s = 0.5
ema_half_life = 2.0

[strategy.avellaneda.penetration]
window_len = 120
num_bins = 500
interval_ms = 500

[strategy.avellaneda.sequencer]
interval_ms = 500

[data]
from_csv = true
tardis_root = "example/data_sample/"
trades_csv = "trades.csv.gz"
quotes_csv = "quotes.csv.gz"
book_csv = "book.csv.gz"

[execution]
latency_ms = 0

[output]
csv_path = "example/run/"
exchange = "bitmex"
date = "01_08_2024"
candle_size_min = 1

[position]
contract_type = "Inverse"
fee_rate = 0.0005

